doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'App\Verification\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Verification/Infrastructure/Doctrine/Migrations'
        'App\Template\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Template/Infrastructure/Doctrine/Migrations'
        'App\Notification\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Notification/Infrastructure/Doctrine/Migrations'
    enable_profiler: false
