version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '64001:8025'

    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=main
        ports:
            - '64004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '64000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    php-consumer:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        command: [ "php", "bin/console", "messenger:consume", "async", "--limit=10" ]
        depends_on:
            - php-fpm
            - rabbitmq
        restart: always

    rabbitmq:
        container_name: sunfinance-verif-rabbitmq
        image: 'rabbitmq:3.10.5-management'
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
