controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

verification_create:
    resource:
        path: ../src/Verification/UI/HTTP
        namespace: App\Verification\UI\HTTP
        methods: [ POST ]
    type: attribute

template_render:
    resource:
        path: ../src/Template/UI/HTTP
        namespace: App\Template\UI\HTTP
        methods: [ POST ]
    type: attribute
